import assets from "./assets";

export const Items = [
    {
      id: 1,
      category: 'Todos-Ladrillo',
      productName: 'Ladrillo Hueco',
      presentation:  "8 x 18 x 33 cm.",
      productPrice: 98,
      description:
          "El ladrillo hueco es un tipo de ladrillo que tiene la característica de tener unos orificios pasantes en su interior en sentido longitudinal. El volumen total de los huecos debe ser igual o mayor al 70% del volumen total del ladrillo.",
      isOff: true,
      offPercentage: 10,
      productImage: require("../assets/images/Mats/LadrilloH/LadrilloH-8x18x33.jpg"),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/LadrilloH/LadrilloH-8x18x33.jpg"),
        require("../assets/images/Mats/LadrilloH/LadrilloH-8x18x33.jpg"),
        require("../assets/images/Mats/LadrilloH/LadrilloH-8x18x33.jpg"),
      ],
      bids: [
        {
          id: "PROV-11",
          name: "Bercovich",
          price: 98,
          image: assets.Bercovich,
          date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-12",
          name: "Rosso Materiales",
          price: 100,
          image: assets.Rosso,
          date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-13",
          name: "Distribuidora Lamadrid",
          price: 98,
          image: assets.Distlam,
          date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
        },
      ],
    },
    {
      id: 2,
      category: 'Todos-Cemento',
      productName: 'Pegamento de pisos Weber impermeable - Pro',
      presentation: "Bolsa de 30 Kgs.",
      productPrice: 2996,
      description:
        "Colocación de piezas con o sin absorción (cerámicas, gres y porcellanatos) en suelos de hormigón o carpeta cementicia, muros de revoques convencionales. Apta para porcellanatos hasta 60x60. Beneficios: Impermeable, para cerámicas y porcellanatos grandes hasta 60x60cm., y para cerámicas exteriores",
      isOff: false,
      productImage: require('../assets/images/Mats/Weber/weber-pro.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Weber/weber-pro.jpg"),
        require("../assets/images/Mats/Weber/weber-pro.jpg"),
        require("../assets/images/Mats/Weber/weber-pro.jpg"),
      ],
      bids: [
        {
          id: "PROV-21",
          name: "Bercovich",
          price: 1890,
          image: assets.Bercovich,
          date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-22",
          name: "Rosso Materiales",
          price: 1899,
          image: assets.Rosso,
          date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-23",
          name: "Distribuidora Lamadrid",
          price: 1910,
          image: assets.Distlam,
          date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
        },
      ],
    },
    {
      id: 3,
      category: 'Todos-Cemento',
      productName: 'Pegamento de pisos Weber impermeable - Basic',
      presentation: "Bolsa de 30 Kgs.",
      productPrice: 1271,
      description:
        "Colocación de piezas con o sin absorción (cerámicas, gres y porcellanatos) en suelos de hormigón o carpeta cementicia, muros de revoques convencionales. Apta para porcellanatos hasta 60x60. Beneficios: Impermeable, para cerámicas y porcellanatos grandes hasta 60x60cm., y para cerámicas exteriores",
      isOff: false,
      productImage: require('../assets/images/Mats/Weber/weber-basic.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Weber/weber-basic.jpg"),
        require("../assets/images/Mats/Weber/weber-basic.jpg"),
        require("../assets/images/Mats/Weber/weber-basic.jpg"),
      ],
      bids: [
        {
          id: "PROV-21",
          name: "Bercovich",
          price: 1890,
          image: assets.Bercovich,
          date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-22",
          name: "Rosso Materiales",
          price: 1899,
          image: assets.Rosso,
          date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-23",
          name: "Distribuidora Lamadrid",
          price: 1910,
          image: assets.Distlam,
          date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
        },
      ],
    },
    {
      id: 4,
      category: 'Todos-Cemento',
      productName: 'Pegamento de pisos Weber impermeable - Gris',
      presentation: "Bolsa de 30 Kgs.",
      productPrice: 1472,
      description:
        "Colocación de piezas con o sin absorción (cerámicas, gres y porcellanatos) en suelos de hormigón o carpeta cementicia, muros de revoques convencionales. Apta para porcellanatos hasta 60x60. Beneficios: Impermeable, para cerámicas y porcellanatos grandes hasta 60x60cm., y para cerámicas exteriores",
      isOff: false,
      productImage: require('../assets/images/Mats/Weber/weber-gris.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Weber/weber-gris.jpg"),
        require("../assets/images/Mats/Weber/weber-gris.jpg"),
        require("../assets/images/Mats/Weber/weber-gris.jpg"),
      ],
      bids: [
        {
          id: "PROV-21",
          name: "Bercovich",
          price: 1890,
          image: assets.Bercovich,
          date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-22",
          name: "Rosso Materiales",
          price: 1899,
          image: assets.Rosso,
          date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-23",
          name: "Distribuidora Lamadrid",
          price: 1910,
          image: assets.Distlam,
          date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
        },
      ],
    },
    {
      id: 5,
      category: 'Todos-Cemento',
      productName: 'Pegamento de pisos Weber impermeable - Porcellanato',
      presentation: "Bolsa de 30 Kgs.",
      productPrice: 4202,
      description:
        "Colocación de piezas con o sin absorción (cerámicas, gres y porcellanatos) en suelos de hormigón o carpeta cementicia, muros de revoques convencionales. Apta para porcellanatos hasta 60x60. Beneficios: Impermeable, para cerámicas y porcellanatos grandes hasta 60x60cm., y para cerámicas exteriores",
      isOff: false,
      productImage: require('../assets/images/Mats/Weber/weber-porcellanato.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Weber/weber-porcellanato.jpg"),
        require("../assets/images/Mats/Weber/weber-porcellanato.jpg"),
        require("../assets/images/Mats/Weber/weber-porcellanato.jpg"),
      ],
      bids: [
        {
          id: "PROV-21",
          name: "Bercovich",
          price: 1890,
          image: assets.Bercovich,
          date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-22",
          name: "Rosso Materiales",
          price: 1899,
          image: assets.Rosso,
          date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-23",
          name: "Distribuidora Lamadrid",
          price: 1910,
          image: assets.Distlam,
          date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
        },
      ],
    },
    {
      id: 6,
      category: 'Todos-Cemento',
      productName: 'Pegamento de pisos Weber impermeable - Con Ceresita',
      presentation: "Bolsa de 30 Kgs.",
      productPrice: 1724,
      description:
        "Colocación de piezas con o sin absorción (cerámicas, gres y porcellanatos) en suelos de hormigón o carpeta cementicia, muros de revoques convencionales. Apta para porcellanatos hasta 60x60. Beneficios: Impermeable, para cerámicas y porcellanatos grandes hasta 60x60cm., y para cerámicas exteriores",
      isOff: false,
      productImage: require('../assets/images/Mats/Weber/weber-imp-cer.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Weber/weber-imp-cer.jpg"),
        require("../assets/images/Mats/Weber/weber-imp-cer.jpg"),
        require("../assets/images/Mats/Weber/weber-imp-cer.jpg"),
      ],
      bids: [
        {
          id: "PROV-21",
          name: "Bercovich",
          price: 1890,
          image: assets.Bercovich,
          date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-22",
          name: "Rosso Materiales",
          price: 1899,
          image: assets.Rosso,
          date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-23",
          name: "Distribuidora Lamadrid",
          price: 1910,
          image: assets.Distlam,
          date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
        },
      ],
    },
    {
      id: 7,
      category: 'Todos-Herramientas',
      productName: "Electrodos para soldar Conarco - Punta Azul",
      presentation: "Venta por 1 Kg.",
      productPrice: 1350,
      description:
        "Klaukol Impermeable Potenciado es un adhesivo para la colocación de pisos y revestimientos cerámicos de media y alta absorción. Es una mezcla en polvo a base cementicia, arenas de granulometría seleccionada, resinas sintéticas y aditivos especiales que garantizan una perfecta adhesión.",
      isOff: true,
      offPercentage: 18,
      productImage: require('../assets/images/Mats/Electrodos-conarco.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Electrodos-conarco.jpg"),
        require("../assets/images/Mats/Electrodos-conarco.jpg"),
        require("../assets/images/Mats/Electrodos-conarco.jpg"),
      ],
      bids: [
        {
          id: "PROV-31",
          name: "Bercovich",
          price: 1700,
          image: assets.Bercovich,
          date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-32",
          name: "Rosso Materiales",
          price: 1620,
          image: assets.Rosso,
          date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-33",
          name: "Distribuidora Lamadrid",
          price: 1650,
          image: assets.Distlam,
          date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
        },
      ],
    },
    {
      id: 8,
      category: 'Todos-Alambre',
      productName: 'Alambre Galvanizado Acindar',
      presentation: "1,6 mm. de espesor - Rollo x 1 Kg.",
      productPrice: 1233,
      description:
        "Es una alambre brillante que se ha sometido a un recubrimiento por inmersión de zinc fundido o por electrólosis, este proceso mejora la resistencia a la corrosión del acero y generalmente, se modifican las propiedades mecánicas mediante tratamientos térmicos, ofreciendo diferentes clases de productos como alambres galvanizados suaves en estado recocido alto, alambres galvanizados medios en estado recocido intermedio, alambres galvanizados sin recocido.",
      isOff: false,
      productImage: require('../assets/images/Mats/Alambre.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Alambre.jpg"),
        require("../assets/images/Mats/Alambre.jpg"),
        require("../assets/images/Mats/Alambre.jpg"),
      ],
      bids: [
        {
          id: "PROV-31",
          name: "Bercovich",
          price: 1240,
          image: assets.Bercovich,
          date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-32",
          name: "Rosso Materiales",
          price: 1233,
          image: assets.Rosso,
          date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-33",
          name: "Distribuidora Lamadrid",
          price: 1300,
          image: assets.Distlam,
          date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
        },
      ],
    },
    {
      id: 9,
      category: 'Todos-Tornillos',
      productName: "Tornillos FIX rosca gruesa",
      presentation: "Negro - x1000 u.",
      productPrice: 2530,
      description:
        "Este tipo de tornillos fix para metal tienen rosca fina y cuenta con una punta aguda tipo aguja, que no necesita de perforación preliminar gracias a su cuerpo delgado y sus filetes en las roscas cortantes, las cuales facilitan su penetración y ensamble.",
      isOff: false,
      productImage: require('../assets/images/Mats/Tornillos.jpeg'),
      isAvailable: false,
      productImageList: [
        require("../assets/images/Mats/Tornillos.jpeg"),
        require("../assets/images/Mats/Tornillos.jpeg"),
        require("../assets/images/Mats/Tornillos.jpeg"),
      ],
      bids: [
        {
          id: "PROV-31",
          name: "Bercovich",
          price: 2535,
          image: assets.Bercovich,
          date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-32",
          name: "Rosso Materiales",
          price: 2535,
          image: assets.Rosso,
          date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-33",
          name: "Distribuidora Lamadrid",
          price: 2530,
          image: assets.Distlam,
          date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
        },
      ],
    },
    {
      id: 10,
      category: 'Todos-Hierro',
      productName: 'Hierro torsionado de 8mm.',
      presentation: "Varillas x 12mts. (x10 u.)",
      productPrice: 18550,
      description:
        "El hierro ADN-420 (dureza natural) o hierro torsionado es un acero al carbono destinado a la construcción. Su superficie es conformada con dos nervaduras longitudinales, y nervaduras transversales a la barra.",
      isOff: false,
      productImage: require('../assets/images/Mats/Hierro.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Hierro.jpg"),
        require("../assets/images/Mats/Hierro.jpg"),
        require("../assets/images/Mats/Hierro.jpg"),
      ],
      bids: [
        {
          id: "PROV-31",
          name: "Bercovich",
          price: 18550,
          image: assets.Bercovich,
          date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-32",
          name: "Rosso Materiales",
          price: 19000,
          image: assets.Rosso,
          date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
        },
        {
          id: "PROV-33",
          name: "Distribuidora Lamadrid",
          price: 18830,
          image: assets.Distlam,
          date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
        },
      ],
    },
    {
      id: 11,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Siena',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 12,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Negra',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 13,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Nacar',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 14,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Marfil',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 15,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Gris Plomo',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 16,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Gris Claro',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 17,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Chocolate',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 18,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Blanca',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 19,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Arena',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 20,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Terracota',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 21,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol - Gris',
      presentation: "Alta Performance - Bolsa 1 Kg.",
      productPrice: 826,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-aperf.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-aperf.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-aperf.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 22,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Blenda',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 23,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Teja',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 24,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Talco',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 25,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Opalo',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 26,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Oliviana',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 27,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Mercurio',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 28,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Hulla',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 29,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Estaño',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 30,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Cobre',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 31,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Caoba',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 32,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Bruma',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
    {
      id: 33,
      category: 'Todos-Cemento',
      productName: 'Pastina Klaukol impermeable antihongos - Boreal',
      presentation: "Bolsa 1 Kg.",
      productPrice: 338,
      description:
        "Ideal para el tomado de juntas de hasta 15mm en todo tipo de placas. Pisos y revestimientos cerámicos, graníticos y calcáreos de todo tipo. Monococción, vicri y porcellanatos en interior y exterior, incluso en baños, balcones y terrazas.",
      isOff: false,
      productImage: require('../assets/images/Mats/Klaukol/klaukol-fluida.jpg'),
      isAvailable: true,
      productImageList: [
        require("../assets/images/Mats/Klaukol/klaukol-fluida.jpg"),
        require("../assets/images/Mats/Klaukol/klaukol-paleta-colores-fluida.jpg"),
      ],
      bids: [
      {
        id: "PROV-31",
        name: "Bercovich",
        price: 7780,
        image: assets.Bercovich,
        date: "Av. 24 de Septiembre 744, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-32",
        name: "Rosso Materiales",
        price: 7740,
        image: assets.Rosso,
        date: "Av. Alem 595, San Miguel de Tucumán, Tucumán",
      },
      {
        id: "PROV-33",
        name: "Distribuidora Lamadrid",
        price: 7740,
        image: assets.Distlam,
        date: "Av. Ejército del Nte. 395, San Miguel de Tucumán, Tucumán",
      },
    ],
    },
  ];